export const  APPLY_COURSE_REQUEST="APPLY_COURSE_REQUEST";
export const APPLY_COURSE_SUCCESS='APPLY_COURSE_SUCCESS';
export const APPLY_COURSE_ERROR='APPLY_COURSE_ERROR'
export const MSAT_REGISTER= 'MSAT_REGISTER';