 export const POST_EVENT_REGISTER_REQUEST='POST_EVENT_REGISTER_REQUEST';
 export const POST_EVENT_REGISTER_SUCCESS='POST_EVENT_REGISTER_SUCCESS'
 export const POST_EVENT_REGISTER_ERROR='POST_EVENT_REGISTER_ERROR'

 export const GET_EVENT_REGISTER_REQUEST="GET_EVENT_REGISTER_REQUEST";
 export const GET_EVENT_REGISTER_SUCCESS="GET_EVENT_REGISTER_SUCCESS";
 export const GET_EVENT_REGISTER_ERROR="GET_EVENT_REGISTER_ERROR"
