export const GET_EVENT = "GET_EVENT";
export const LOADING_EVENT = "LOADING_EVENT";
export const ERROR_EVENT = "ERROR_EVENT";

export const GET_SINGLE_EVENT = "GET_SINGLE_EVENT";
export const LOADING_SINGLE_EVENT = "LOADING_SINGLE_EVENT";
export const ERROR_SINGLE_EVENT = "ERROR_SINGLE_EVENT";
